name: Build

于:
  workflow_dispatch:
    inputs:
      package_name:
        description: "Target package name"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Prepare Gradle
        run: chmod +x ./gradlew

      - name: Configure package name
        run: |
          sed -i 's/moduleDescription = "/moduleDescription = "(${{ github.event.inputs.package_name }}) /g' module.gradle
          sed -i "s/com.game.packagename/${{ github.event.inputs.package_name }}/g" module/src/main/cpp/game.h

      - name: Build release APK
        run: ./gradlew :module:assembleRelease

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: zygisk-il2cppdumper
          path: out/magisk_module_release/
